# Generated by Django 5.0.1 on 2024-01-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('revenue', models.DecimalField(decimal_places=4, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=4, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('financial_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataVizUploader.financialfile')),
            ],
        ),
    ]
