# Generated by Django 4.2.9 on 2024-01-27 16:53

import DataVizUploader.models
import DataVizUploader.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataVizUploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialfile',
            name='file',
            field=models.FileField(upload_to=DataVizUploader.models.FinancialFile.files_directory_path, validators=[DataVizUploader.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'doc', 'docx', 'pdf', 'ppt', 'pptx', 'csv'])]),
        ),
    ]
